### ISSUE TITLE
Name reference to old developer role

### ISSUE THREAD

**Issue by Noxturnix** [psych2go-devs/psych2go-bot#15]
~Allow 3rd role permission: Community Helper.~
See [this comment](https://github.com/psych2go-devs/psych2go-bot/issues/15#issuecomment-1837278891).

**Comment by Noxturnix** [comment]
My bad. There exists an environment variable `STAFF_ROLE_ID` that accepts multiple comma-separated role IDs. However, there are some old variables/properties reference to the developer role. For example, `devRoleIds` in lib/roleId.ts. These names still need to be updated.

**Comment by komotok** [comment]
Just pushed a request for this with messageCreate.ts

**Comment by Noxturnix** [comment]
Thanks
